In [12]:
install.packages("gt")
install.packages("tidyverse")
install.packages("dplyr")
library(dplyr)
# Load the neessary packages
library(gt)
library(tidyverse)

# Create a sample data frame
data <- tibble(
  Var1 = c("A", "B", "C"),
  Var2 = c("A", "B", "C"),
  Freq = c(0, 1, 0)
)

# Create a gt table
table <- gt(data)

# Display the table
table

The downloaded binary packages are in
	/var/folders/4n/vzp_j0lx35vdvg37_j9kwnj00000gp/T//Rtmpr4TnG6/downloaded_packages

Warning message:
“package ‘tidyvers’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages”

The downloaded binary packages are in
	/var/folders/4n/vzp_j0lx35vdvg37_j9kwnj00000gp/T//Rtmpr4TnG6/downloaded_packages

<div id="hbqcjgymxx" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
  <style>#hbqcjgymxx table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#hbqcjgymxx thead, #hbqcjgymxx tbody, #hbqcjgymxx tfoot, #hbqcjgymxx tr, #hbqcjgymxx td, #hbqcjgymxx th {
  border-style: none;
}

#hbqcjgymxx p {
  margin: 0;
  padding: 0;
}

#hbqcjgymxx .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#hbqcjgymxx .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#hbqcjgymxx .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#hbqcjgymxx .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#hbqcjgymxx .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hbqcjgymxx .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hbqcjgymxx .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hbqcjgymxx .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#hbqcjgymxx .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#hbqcjgymxx .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#hbqcjgymxx .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#hbqcjgymxx .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#hbqcjgymxx .gt_spanner_row {
  border-bottom-style: hidden;
}

#hbqcjgymxx .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#hbqcjgymxx .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#hbqcjgymxx .gt_from_md > :first-child {
  margin-top: 0;
}

#hbqcjgymxx .gt_from_md > :last-child {
  margin-bottom: 0;
}

#hbqcjgymxx .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#hbqcjgymxx .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#hbqcjgymxx .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#hbqcjgymxx .gt_row_group_first td {
  border-top-width: 2px;
}

#hbqcjgymxx .gt_row_group_first th {
  border-top-width: 2px;
}

#hbqcjgymxx .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hbqcjgymxx .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#hbqcjgymxx .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#hbqcjgymxx .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hbqcjgymxx .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hbqcjgymxx .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#hbqcjgymxx .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#hbqcjgymxx .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#hbqcjgymxx .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hbqcjgymxx .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hbqcjgymxx .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#hbqcjgymxx .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hbqcjgymxx .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#hbqcjgymxx .gt_left {
  text-align: left;
}

#hbqcjgymxx .gt_center {
  text-align: center;
}

#hbqcjgymxx .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#hbqcjgymxx .gt_font_normal {
  font-weight: normal;
}

#hbqcjgymxx .gt_font_bold {
  font-weight: bold;
}

#hbqcjgymxx .gt_font_italic {
  font-style: italic;
}

#hbqcjgymxx .gt_super {
  font-size: 65%;
}

#hbqcjgymxx .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#hbqcjgymxx .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#hbqcjgymxx .gt_indent_1 {
  text-indent: 5px;
}

#hbqcjgymxx .gt_indent_2 {
  text-indent: 10px;
}

#hbqcjgymxx .gt_indent_3 {
  text-indent: 15px;
}

#hbqcjgymxx .gt_indent_4 {
  text-indent: 20px;
}

#hbqcjgymxx .gt_indent_5 {
  text-indent: 25px;
}
</style>
  <table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>

    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Var1">Var1</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Var2">Var2</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Freq">Freq</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="Var1" class="gt_row gt_left">A</td>
<td headers="Var2" class="gt_row gt_left">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_left">B</td>
<td headers="Var2" class="gt_row gt_left">B</td>
<td headers="Freq" class="gt_row gt_right">1</td></tr>
    <tr><td headers="Var1" class="gt_row gt_left">C</td>
<td headers="Var2" class="gt_row gt_left">C</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
  </tbody>


</table>
</div>

In [9]:
library(dplyr)
library(gt)
library(tidyvers)



# Estimated world population and continent populations in 2021
world_pop_2021 <- 7.8e9
continent_pop_2021 <- data.frame(
  continent = c("Africa", "Asia", "Europe", "North America", "South America", "Australia"),
  population = c(1.3e9, 4.7e9, 747e6, 592e6, 430e6, 39e6),
  population_density = c(44, 150, 73, 23, 24, 3),
  average_annual_wage = c(3000, 10000, 40000, 40000, 15000, 50000)
)

# Sample housing type percentages for each continent
housing_types <- c("detached", "apartment", "factory_dorm", "townhouse", "duplex", "bungalow", "mobile_home", "co_housing", "informal_settlement", "villa")

housing_data <- data.frame(
  continent = rep(c("Africa", "Asia", "Europe", "North America", "South America", "Australia"), each = length(housing_types)),
  housing_type = rep(housing_types, 6),
  housing_type_percentage = c(
    40, 20, 5, 5, 5, 5, 5, 5, 5, 0,
    30, 40, 5, 5, 5, 5, 0, 5, 0, 5,
    30, 40, 0, 10, 5, 5, 0, 0, 0, 10,
    40, 30, 0, 5, 10, 5, 5, 0, 0, 5,
    40, 30, 0, 10, 5, 5, 5, 0, 0, 5,
    50, 10, 0, 10, 5, 10, 0, 5, 0, 10
  )
)

# Scale the population to 5000
scaled_continent_pop <- continent_pop_2021 %>%
  mutate(
    scaled_population = (population / world_pop_2021) * 5000
  )

# Join the housing data with the scaled continent population data
scaled_continent_pop_housing <- scaled_continent_pop %>%
  inner_join(housing_data, by = "continent") %>%
  mutate(
    housing_population = round(scaled_population * housing_type_percentage / 100)
  )

# Perform cross-tabulation and create a three-way table
three_way_table <- with(scaled_continent_pop_housing, ftable(continent, housing_type, housing_population))

# Convert the ftable to a data frame
three_way_table_df <- as.data.frame.table(three_way_table)

# Display the table using the gt library
three_way_table_df %>%
  gt() %>%
  tab_header(
    title = "Three-way table of continent, housing type, and housing population",
    subtitle = "Scaled to a total world population of 5,000"
  )

<div id="yvwpmxugcv" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
  <style>#yvwpmxugcv table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#yvwpmxugcv thead, #yvwpmxugcv tbody, #yvwpmxugcv tfoot, #yvwpmxugcv tr, #yvwpmxugcv td, #yvwpmxugcv th {
  border-style: none;
}

#yvwpmxugcv p {
  margin: 0;
  padding: 0;
}

#yvwpmxugcv .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#yvwpmxugcv .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#yvwpmxugcv .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#yvwpmxugcv .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#yvwpmxugcv .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#yvwpmxugcv .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#yvwpmxugcv .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#yvwpmxugcv .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#yvwpmxugcv .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#yvwpmxugcv .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#yvwpmxugcv .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#yvwpmxugcv .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#yvwpmxugcv .gt_spanner_row {
  border-bottom-style: hidden;
}

#yvwpmxugcv .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#yvwpmxugcv .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#yvwpmxugcv .gt_from_md > :first-child {
  margin-top: 0;
}

#yvwpmxugcv .gt_from_md > :last-child {
  margin-bottom: 0;
}

#yvwpmxugcv .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#yvwpmxugcv .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#yvwpmxugcv .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#yvwpmxugcv .gt_row_group_first td {
  border-top-width: 2px;
}

#yvwpmxugcv .gt_row_group_first th {
  border-top-width: 2px;
}

#yvwpmxugcv .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#yvwpmxugcv .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#yvwpmxugcv .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#yvwpmxugcv .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#yvwpmxugcv .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#yvwpmxugcv .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#yvwpmxugcv .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#yvwpmxugcv .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#yvwpmxugcv .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#yvwpmxugcv .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#yvwpmxugcv .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#yvwpmxugcv .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#yvwpmxugcv .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#yvwpmxugcv .gt_left {
  text-align: left;
}

#yvwpmxugcv .gt_center {
  text-align: center;
}

#yvwpmxugcv .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#yvwpmxugcv .gt_font_normal {
  font-weight: normal;
}

#yvwpmxugcv .gt_font_bold {
  font-weight: bold;
}

#yvwpmxugcv .gt_font_italic {
  font-style: italic;
}

#yvwpmxugcv .gt_super {
  font-size: 65%;
}

#yvwpmxugcv .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#yvwpmxugcv .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#yvwpmxugcv .gt_indent_1 {
  text-indent: 5px;
}

#yvwpmxugcv .gt_indent_2 {
  text-indent: 10px;
}

#yvwpmxugcv .gt_indent_3 {
  text-indent: 15px;
}

#yvwpmxugcv .gt_indent_4 {
  text-indent: 20px;
}

#yvwpmxugcv .gt_indent_5 {
  text-indent: 25px;
}
</style>
  <table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_heading">
      <td colspan="3" class="gt_heading gt_title gt_font_normal" style>Three-way table of continent, housing type, and housing population</td>
    </tr>
    <tr class="gt_heading">
      <td colspan="3" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style>Scaled to a total world population of 5,000</td>
    </tr>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="Var1">Var1</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="Var2">Var2</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Freq">Freq</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="Var1" class="gt_row gt_center">A</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">B</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">C</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">D</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">E</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">F</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">G</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">H</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">I</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">J</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">1</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">K</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">L</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">M</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">N</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">O</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">P</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">Q</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">1</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">R</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">1</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">S</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">T</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">U</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">V</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">W</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">X</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">Y</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">Z</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">1</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">A1</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">1</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">B1</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">1</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">C1</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">D1</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">E1</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">F1</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">G1</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">1</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">H1</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">I1</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">J1</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">1</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">K1</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">1</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">L1</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">1</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">M1</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">N1</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">O1</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">P1</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">Q1</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">1</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">R1</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">S1</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">T1</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">1</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">U1</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">1</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">V1</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">W1</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">X1</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">Y1</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">Z1</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">A2</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">1</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">B2</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">C2</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">D2</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">1</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">E2</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">1</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">F2</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">G2</td>
<td headers="Var2" class="gt_row gt_center">A</td>
<td headers="Freq" class="gt_row gt_right">0</td></tr>
    <tr><td headers="Var1" class="gt_row gt_center">H2</td>
<td headers="Var2" class="gt_row gt_center">A</td>

In [10]:
library(dplyr)

# Estimated world population and continent populations in 2021
world_pop_2021 <- 7.8e9
continent_pop_2021 <- data.frame(
  continent = c("Africa", "Asia", "Europe", "North America", "South America", "Australia"),
  population = c(1.3e9, 4.7e9, 747e6, 592e6, 430e6, 39e6),
  population_density = c(44, 150, 73, 23, 24, 3),
  average_annual_wage = c(3000, 10000, 40000, 40000, 15000, 50000)
)

# Sample housing type percentages for each continent
housing_types <- c("detached", "apartment", "factory_dorm", "townhouse", "duplex", "bungalow", "mobile_home", "co_housing", "informal_settlement", "villa")

housing_data <- data.frame(
  continent = rep(c("Africa", "Asia", "Europe", "North America", "South America", "Australia"), each = length(housing_types)),
  housing_type = rep(housing_types, 6),
  housing_type_percentage = c(
    40, 20, 5, 5, 5, 5, 5, 5, 5, 0,
    30, 40, 5, 5, 5, 5, 0, 5, 0, 5,
    30, 40, 0, 10, 5, 5, 0, 0, 0, 10,
    40, 30, 0, 5, 10, 5, 5, 0, 0, 5,
    40, 30, 0, 10, 5, 5, 5, 0, 0, 5,
    50, 10, 0, 10, 5, 10, 0, 5, 0, 10
  )
)

# Scale the population to 5000
scaled_continent_pop <- continent_pop_2021 %>%
  mutate(
    scaled_population = (population / world_pop_2021) * 5000
  )

# Join the housing data with the scaled continent population data
scaled_continent_pop_housing <- scaled_continent_pop %>%
  inner_join(housing_data, by = "continent") %>%
  mutate(
    housing_population = round(scaled_population * housing_type_percentage / 100)
  )

# Perform cross-tabulation and create a three-way table
three_way_table <- with(scaled_continent_pop_housing, ftable(continent, housing_type, housing_population))
print(three_way_table)

                                  housing_population 0 1 2 12 14 19 24 28 38 42 48 83 110 114 144 151 152 167 192 333 904 1205
continent     housing_type
Africa        apartment                              0 0 0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   1   0   0   0    0
              bungalow                               0 0 0  0  0  0  0  0  0  1  0  0   0   0   0   0   0   0   0   0   0    0
              co_housing                             0 0 0  0  0  0  0  0  0  1  0  0   0   0   0   0   0   0   0   0   0    0
              detached                               0 0 0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   1   0    0
              duplex                                 0 0 0  0  0  0  0  0  0  1  0  0   0   0   0   0   0   0   0   0   0    0
              factory_dorm                           0 0 0  0  0  0  0  0  0  1  0  0   0   0   0   0   0   0   0   0   0    0
              informal_settlement                    0 0 0  0  0  0  0  0  0  1  0  0   0   0   0   0   0   0   0   0   0    0
              mobile_home                            0 0 0  0  0  0  0  0  0  1  0  0   0   0   0   0   0   0   0   0   0    0
              townhouse                              0 0 0  0  0  0  0  0  0  1  0  0   0   0   0   0   0   0   0   0   0    0
              villa                                  1 0 0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
Asia          apartment                              0 0 0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    1
              bungalow                               0 0 0  0  0  0  0  0  0  0  0  0   0   0   0   1   0   0   0   0   0    0
              co_housing                             0 0 0  0  0  0  0  0  0  0  0  0   0   0   0   1   0   0   0   0   0    0
              detached                               0 0 0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   1    0
              duplex                                 0 0 0  0  0  0  0  0  0  0  0  0   0   0   0   1   0   0   0   0   0    0
              factory_dorm                           0 0 0  0  0  0  0  0  0  0  0  0   0   0   0   1   0   0   0   0   0    0
              informal_settlement                    1 0 0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
              mobile_home                            1 0 0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
              townhouse                              0 0 0  0  0  0  0  0  0  0  0  0   0   0   0   1   0   0   0   0   0    0
              villa                                  0 0 0  0  0  0  0  0  0  0  0  0   0   0   0   1   0   0   0   0   0    0
Australia     apartment                              0 0 1  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
              bungalow                               0 0 1  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
              co_housing                             0 1 0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
              detached                               0 0 0  1  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
              duplex                                 0 1 0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
              factory_dorm                           1 0 0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
              informal_settlement                    1 0 0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
              mobile_home                            1 0 0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
              townhouse                              0 0 1  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
              villa                                  0 0 1  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
Europe        apartment                              0 0 0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   1   0   0    0
              bungalow                               0 0 0  0  0  0  1  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
              co_housing                             1 0 0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
              detached                               0 0 0  0  0  0  0  0  0  0  0  0   0   0   1   0   0   0   0   0   0    0
              duplex                                 0 0 0  0  0  0  1  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
              factory_dorm                           1 0 0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
              informal_settlement                    1 0 0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
              mobile_home                            1 0 0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
              townhouse                              0 0 0  0  0  0  0  0  0  0  1  0   0   0   0   0   0   0   0   0   0    0
              villa                                  0 0 0  0  0  0  0  0  0  0  1  0   0   0   0   0   0   0   0   0   0    0
North America apartment                              0 0 0  0  0  0  0  0  0  0  0  0   0   1   0   0   0   0   0   0   0    0
              bungalow                               0 0 0  0  0  1  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
              co_housing                             1 0 0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
              detached                               0 0 0  0  0  0  0  0  0  0  0  0   0   0   0   0   1   0   0   0   0    0
              duplex                                 0 0 0  0  0  0  0  0  1  0  0  0   0   0   0   0   0   0   0   0   0    0
              factory_dorm                           1 0 0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
              informal_settlement                    1 0 0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
              mobile_home                            0 0 0  0  0  1  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
              townhouse                              0 0 0  0  0  1  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
              villa                                  0 0 0  0  0  1  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
South America apartment                              0 0 0  0  0  0  0  0  0  0  0  1   0   0   0   0   0   0   0   0   0    0
              bungalow                               0 0 0  0  1  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
              co_housing                             1 0 0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
              detached                               0 0 0  0  0  0  0  0  0  0  0  0   1   0   0   0   0   0   0   0   0    0
              duplex                                 0 0 0  0  1  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
              factory_dorm                           1 0 0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
              informal_settlement                    1 0 0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
              mobile_home                            0 0 0  0  1  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0
              townhouse                              0 0 0  0  0  0  0  1  0  0  0  0   0   0   0   0   0   0   0   0   0    0
              villa                                  0 0 0  0  1  0  0  0  0  0  0  0   0   0   0   0   0   0   0   0   0    0